[tool.isort]
profile = "black"

[tool.black]
line-length = 120
target-version = ['py38']
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.ruff]
line-length = 120
extend-exclude = ["*/migrations/*"]