# Generated by Django 5.0.6 on 2024-06-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titulek")),
                ("content", models.TextField(verbose_name="obsah")),
                (
                    "full_image",
                    models.ImageField(upload_to="articles/", verbose_name="obrázek"),
                ),
                (
                    "image_thumb",
                    models.ImageField(blank=True, upload_to="articles/thumbs/"),
                ),
            ],
            options={
                "verbose_name": "článek",
                "verbose_name_plural": "články",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "tag", "verbose_name_plural": "tagy"},
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="tag"),
        ),
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blog.article"),
                ),
                (
                    "tag",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="blog.tag"),
                ),
            ],
            options={
                "unique_together": {("article", "tag")},
            },
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="articles",
                through="blog.ArticleTag",
                to="blog.tag",
                verbose_name="tagy",
            ),
        ),
    ]
